services:
  paralyabot-cache:
    image: ghcr.io/e-psi-lon/paralyabot-cache:latest
    container_name: paralyabot-cache
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "/app/paralyabot-cache", "-healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  paralyabot:
    image: ghcr.io/e-psi-lon/paralyabot:latest
    container_name: paralyabot
    volumes:
      - ./container:/app/external
    environment:
      - KORD_CACHE_URL=redis://paralyabot-cache:6379
    restart: unless-stopped
    depends_on:
      paralyabot-cache:
        condition: service_healthy