paralyabot.version=1.1.2
plugin.lg.version=0.1.0
plugin.sta.version=0.1.0
module.build-logic.version=1.1.2
module.deps.version=1.1.2
module.common.version=1.1.2
module.common.min-compatible-version=1.0.0
